import type { RecommendationQuery } from "@/lib/domain/contracts";

export type GoldenFixture = {
  name: string;
  query: RecommendationQuery;
  expectedTopIds?: string[];
};

export const goldenFixtures: GoldenFixture[] = [
  { name: "anniversary-october-couple", query: { partyType: "couple", partySize: 2, budgetBand: "mid", tripLengthDays: 5, departureAirport: "ICN", travelMonth: 10, pace: "balanced", flightTolerance: "medium", vibes: ["romance", "food"] }, expectedTopIds: ["lisbon", "chiang-mai", "paris"] },
  { name: "winter-short-haul-couple", query: { partyType: "couple", partySize: 2, budgetBand: "mid", tripLengthDays: 4, departureAirport: "ICN", travelMonth: 1, pace: "slow", flightTolerance: "short", vibes: ["romance", "culture"] }, expectedTopIds: ["macau", "chiang-mai", "phuket"] },
  { name: "friends-summer-budget", query: { partyType: "friends", partySize: 4, budgetBand: "budget", tripLengthDays: 5, departureAirport: "ICN", travelMonth: 7, pace: "packed", flightTolerance: "medium", vibes: ["nightlife", "food"] }, expectedTopIds: ["da-nang", "hoi-an", "sapporo"] },
  { name: "city-shopping-couple", query: { partyType: "couple", partySize: 2, budgetBand: "premium", tripLengthDays: 6, departureAirport: "ICN", travelMonth: 11, pace: "balanced", flightTolerance: "medium", vibes: ["city", "shopping"] }, expectedTopIds: ["los-angeles", "hong-kong", "sydney"] },
  { name: "beach-slow-couple", query: { partyType: "couple", partySize: 2, budgetBand: "mid", tripLengthDays: 6, departureAirport: "ICN", travelMonth: 5, pace: "slow", flightTolerance: "medium", vibes: ["beach", "romance"] }, expectedTopIds: ["bali", "boracay", "da-nang"] },
  { name: "foodie-short-trip", query: { partyType: "friends", partySize: 3, budgetBand: "budget", tripLengthDays: 3, departureAirport: "ICN", travelMonth: 4, pace: "balanced", flightTolerance: "short", vibes: ["food", "city"] }, expectedTopIds: ["taipei", "fukuoka", "kaohsiung"] },
  { name: "culture-long-haul", query: { partyType: "couple", partySize: 2, budgetBand: "premium", tripLengthDays: 9, departureAirport: "ICN", travelMonth: 5, pace: "balanced", flightTolerance: "long", vibes: ["culture", "romance"] }, expectedTopIds: ["paris", "rome", "vienna"] },
  { name: "family-beach-break", query: { partyType: "family", partySize: 4, budgetBand: "mid", tripLengthDays: 5, departureAirport: "ICN", travelMonth: 2, pace: "slow", flightTolerance: "medium", vibes: ["family", "beach"] }, expectedTopIds: ["guam", "saipan", "phuket"] },
  { name: "spring-cafe-city", query: { partyType: "solo", partySize: 1, budgetBand: "mid", tripLengthDays: 5, departureAirport: "ICN", travelMonth: 4, pace: "slow", flightTolerance: "short", vibes: ["city", "culture"] }, expectedTopIds: ["tokyo", "fukuoka", "macau"] },
  { name: "luxury-desert", query: { partyType: "couple", partySize: 2, budgetBand: "premium", tripLengthDays: 7, departureAirport: "ICN", travelMonth: 12, pace: "balanced", flightTolerance: "long", vibes: ["luxury", "desert"] }, expectedTopIds: ["dubai", "vienna", "melbourne"] },
  { name: "new-year-shopping", query: { partyType: "friends", partySize: 3, budgetBand: "premium", tripLengthDays: 4, departureAirport: "ICN", travelMonth: 12, pace: "packed", flightTolerance: "short", vibes: ["shopping", "city"] }, expectedTopIds: ["hong-kong", "tokyo", "osaka"] },
  { name: "early-summer-beach-friends", query: { partyType: "friends", partySize: 4, budgetBand: "mid", tripLengthDays: 5, departureAirport: "ICN", travelMonth: 6, pace: "balanced", flightTolerance: "medium", vibes: ["beach", "nightlife"] }, expectedTopIds: ["boracay", "bali", "barcelona"] },
  { name: "autumn-europe-romance", query: { partyType: "couple", partySize: 2, budgetBand: "premium", tripLengthDays: 8, departureAirport: "ICN", travelMonth: 10, pace: "balanced", flightTolerance: "long", vibes: ["romance", "culture"] }, expectedTopIds: ["paris", "rome", "vienna"] },
  { name: "budget-food-romance", query: { partyType: "couple", partySize: 2, budgetBand: "budget", tripLengthDays: 5, departureAirport: "ICN", travelMonth: 11, pace: "balanced", flightTolerance: "medium", vibes: ["food", "romance"] }, expectedTopIds: ["chiang-mai", "bangkok", "phuket"] },
  { name: "winter-honeymoon-sun", query: { partyType: "couple", partySize: 2, budgetBand: "premium", tripLengthDays: 7, departureAirport: "ICN", travelMonth: 2, pace: "slow", flightTolerance: "long", vibes: ["beach", "romance"] }, expectedTopIds: ["phuket", "boracay", "saipan"] },
  { name: "japan-food-hop", query: { partyType: "friends", partySize: 3, budgetBand: "mid", tripLengthDays: 4, departureAirport: "ICN", travelMonth: 3, pace: "packed", flightTolerance: "short", vibes: ["food", "shopping"] }, expectedTopIds: ["tokyo", "osaka", "taipei"] },
  { name: "quiet-heritage-trip", query: { partyType: "solo", partySize: 1, budgetBand: "mid", tripLengthDays: 6, departureAirport: "ICN", travelMonth: 11, pace: "slow", flightTolerance: "medium", vibes: ["culture", "nature"] }, expectedTopIds: ["chiang-mai", "kyoto", "saipan"] },
  { name: "friends-nightlife-premium", query: { partyType: "friends", partySize: 4, budgetBand: "premium", tripLengthDays: 6, departureAirport: "ICN", travelMonth: 9, pace: "packed", flightTolerance: "medium", vibes: ["nightlife", "shopping"] }, expectedTopIds: ["singapore", "hong-kong", "new-york-city"] },
  { name: "family-city-culture", query: { partyType: "family", partySize: 4, budgetBand: "mid", tripLengthDays: 6, departureAirport: "ICN", travelMonth: 10, pace: "balanced", flightTolerance: "medium", vibes: ["family", "culture"] }, expectedTopIds: ["bali", "guam", "kyoto"] },
  { name: "spring-beach-budget", query: { partyType: "couple", partySize: 2, budgetBand: "budget", tripLengthDays: 5, departureAirport: "ICN", travelMonth: 4, pace: "slow", flightTolerance: "medium", vibes: ["beach", "food"] }, expectedTopIds: ["da-nang", "hoi-an", "kaohsiung"] },
  { name: "late-summer-nature", query: { partyType: "couple", partySize: 2, budgetBand: "mid", tripLengthDays: 6, departureAirport: "ICN", travelMonth: 8, pace: "slow", flightTolerance: "medium", vibes: ["nature", "romance"] }, expectedTopIds: ["bali", "okinawa", "zurich"] },
  { name: "holiday-family-resort", query: { partyType: "family", partySize: 4, budgetBand: "premium", tripLengthDays: 7, departureAirport: "ICN", travelMonth: 12, pace: "slow", flightTolerance: "medium", vibes: ["family", "beach"] }, expectedTopIds: ["guam", "gold-coast", "saipan"] },
  { name: "urban-culture-premium", query: { partyType: "solo", partySize: 1, budgetBand: "premium", tripLengthDays: 7, departureAirport: "ICN", travelMonth: 5, pace: "balanced", flightTolerance: "long", vibes: ["city", "culture"] }, expectedTopIds: ["barcelona", "los-angeles", "new-york-city"] },
  { name: "warm-short-haul-break", query: { partyType: "couple", partySize: 2, budgetBand: "mid", tripLengthDays: 4, departureAirport: "ICN", travelMonth: 3, pace: "balanced", flightTolerance: "short", vibes: ["food", "romance"] }, expectedTopIds: ["tokyo", "kyoto", "macau"] },
  { name: "australia-city-loop", query: { partyType: "friends", partySize: 3, budgetBand: "premium", tripLengthDays: 10, departureAirport: "ICN", travelMonth: 11, pace: "balanced", flightTolerance: "long", vibes: ["city", "nature"] }, expectedTopIds: ["melbourne", "sydney", "los-angeles"] },
  { name: "fashion-photo-trip", query: { partyType: "couple", partySize: 2, budgetBand: "premium", tripLengthDays: 6, departureAirport: "ICN", travelMonth: 4, pace: "balanced", flightTolerance: "long", vibes: ["shopping", "romance"] }, expectedTopIds: ["paris", "honolulu", "rome"] },
  { name: "budget-autumn-friends", query: { partyType: "friends", partySize: 4, budgetBand: "budget", tripLengthDays: 5, departureAirport: "ICN", travelMonth: 10, pace: "balanced", flightTolerance: "medium", vibes: ["food", "nightlife"] }, expectedTopIds: ["bangkok", "osaka", "macau"] },
  { name: "coastal-reset-solo", query: { partyType: "solo", partySize: 1, budgetBand: "mid", tripLengthDays: 6, departureAirport: "ICN", travelMonth: 5, pace: "slow", flightTolerance: "medium", vibes: ["nature", "beach"] }, expectedTopIds: ["bali", "cebu", "saipan"] },
  { name: "city-lights-winter", query: { partyType: "friends", partySize: 3, budgetBand: "premium", tripLengthDays: 5, departureAirport: "ICN", travelMonth: 1, pace: "packed", flightTolerance: "medium", vibes: ["city", "nightlife"] }, expectedTopIds: ["hong-kong", "bangkok", "singapore"] },
  { name: "spring-romance-short-haul", query: { partyType: "couple", partySize: 2, budgetBand: "mid", tripLengthDays: 4, departureAirport: "ICN", travelMonth: 4, pace: "slow", flightTolerance: "short", vibes: ["romance", "nature"] }, expectedTopIds: ["kyoto", "okinawa", "bali"] },
];
